### ISSUE TITLE
Fatal error in shared hosting

### ISSUE THREAD

**Issue by marcmorente** [a2lix/AutoFormBundle#12]
Hello, I get this error on shared hosting.

Fatal error: Uncaught TypeError: Return value of A2lix\AutoFormBundle\DependencyInjection\A2lixAutoFormExtension::load() must be an instance of A2lix\AutoFormBundle\DependencyInjection\void, none returned in /vendor/a2lix/auto-form-bundle/src/DependencyInjection/A2lixAutoFormExtension.php:37 Stack trace: #0 /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php(71): A2lix\AutoFormBundle\DependencyInjection\A2lixAutoFormExtension->load(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder)) #1 /symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #2 /vendor/symfony in vendor/a2lix/auto-form-bundle/src/DependencyInjection/A2lixAutoFormExtension.php on line 37

**Comment by marcmorente** [comment]
But in localhost its working
